export {
  HOME,
  WRITE,
  REGISTER,
  LANDING,
  ADMIN,
  ADDRESS,
  ARTICLE,
  API_GET_ALL_LOCATIONS,
  API_GET_ALL_CATEGORIES,
  API_GET_ALL_ARTICLES,
  VAR_ARRAY_STATES,
  API_GET_ALL_CARDS,
} from "./CONSTANTS";
